/*
    Automatically generated by Fault
    Do not modify.
    Generated on: 2023-10-29 18:47:43
*/

`include "yosys/examples/cmos/cmos_cells.v"
`include "EEGR471/asmd/netlist/asmd_multiplier_netlist.v.chained.v"

`ifndef CLOCK_PERIOD
    `define CLOCK_PERIOD 4
`endif
module testbench;
    wire[0:0] \ready ;
    wire[7:0] \product ;
    reg[3:0] \word0 ;
    reg[0:0] \reset ;
    reg[0:0] \start ;
    wire[0:0] \sout ;
    reg[0:0] \tck ;
    reg[3:0] \word1 ;
    reg[0:0] \test ;
    reg[0:0] \clk ;
    reg[0:0] \sin ;
    reg[0:0] \shift ;

        always #(`CLOCK_PERIOD / 2) clk = ~clk; 
        always #(`CLOCK_PERIOD / 2) tck = ~tck; 

    asmd_multiplier_netlist uut(
        .\ready ( \ready ) , .\product ( \product ) , .\word0 ( \word0 ) , .\reset ( \reset ) , .\start ( \start ) , .\sout ( \sout ) , .\tck ( \tck ) , .\word1 ( \word1 ) , .\test ( \test ) , .\clk ( \clk ) , .\sin ( \sin ) , .\shift ( \shift ) 
    ); 

    wire[38:0] __serializable__ =
        39'b010000001000000111110111001110100010010;
    reg[38:0] __serial__;
    integer i;
    initial begin
        `ifdef VCD
            $dumpfile("chain.vcd");
            $dumpvars(0, testbench);
        `endif
        \word0 = 0 ;
        \word1 = 0 ;
        \start = 0 ;
        \clk = 0 ;
        \reset = 1 ;
        \sin = 0 ;
        \shift = 0 ;
        \tck = 0 ;
        \test = 0 ;

        #(`CLOCK_PERIOD*5);
        reset = ~reset;
        shift = 1;
        test = 1;
        for (i = 0; i < 39; i = i + 1) begin
            sin = __serializable__[i];
            #(`CLOCK_PERIOD);
        end
        for (i = 0; i < 39; i = i + 1) begin
            __serial__[i] = sout;
            #(`CLOCK_PERIOD);
        end
        if (__serial__ === __serializable__) begin
            $display("SUCCESS_STRING");
        end
        $finish;
    end
endmodule
