/*
    Automatically generated by Fault
    Do not modify.
    Generated on: 2023-11-03 23:27:49
*/
/* FAULT METADATA: '{"boundaryCount":18,"sout":"sout","internalCount":21,"sin":"sin","order":[{"kind":"input","ordinal":0,"name":"word0","width":4},{"kind":"input","ordinal":0,"name":"word1","width":4},{"kind":"input","ordinal":0,"name":"start","width":1},{"kind":"dff","ordinal":0,"name":"_400_","width":1},{"kind":"dff","ordinal":0,"name":"_401_","width":1},{"kind":"dff","ordinal":0,"name":"_402_","width":1},{"kind":"dff","ordinal":0,"name":"_403_","width":1},{"kind":"dff","ordinal":0,"name":"_404_","width":1},{"kind":"dff","ordinal":0,"name":"_405_","width":1},{"kind":"dff","ordinal":0,"name":"_406_","width":1},{"kind":"dff","ordinal":0,"name":"_407_","width":1},{"kind":"dff","ordinal":0,"name":"_408_","width":1},{"kind":"dff","ordinal":0,"name":"_409_","width":1},{"kind":"dff","ordinal":0,"name":"_410_","width":1},{"kind":"dff","ordinal":0,"name":"_411_","width":1},{"kind":"dff","ordinal":0,"name":"_412_","width":1},{"kind":"dff","ordinal":0,"name":"_413_","width":1},{"kind":"dff","ordinal":0,"name":"_414_","width":1},{"kind":"dff","ordinal":0,"name":"_415_","width":1},{"kind":"dff","ordinal":0,"name":"_416_","width":1},{"kind":"dff","ordinal":0,"name":"_417_","width":1},{"kind":"dff","ordinal":0,"name":"_418_","width":1},{"kind":"dff","ordinal":0,"name":"_419_","width":1},{"kind":"dff","ordinal":0,"name":"_420_","width":1},{"kind":"output","ordinal":0,"name":"product","width":8},{"kind":"output","ordinal":0,"name":"ready","width":1}],"shift":"shift"}' END FAULT METADATA */
/* Generated by Yosys 0.12+45 (git sha1 UNKNOWN, gcc 8.3.1 -fPIC -Os) */

module asmd_multiplier_netlist(product, ready, word0, word1, start, clk, reset, sin, shift, sout, tck, test);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire \__BoundaryScanRegister_input_0__.dout ;
  wire \__BoundaryScanRegister_input_0__.sout ;
  wire \__BoundaryScanRegister_input_1__.dout ;
  wire \__BoundaryScanRegister_input_1__.sout ;
  wire \__BoundaryScanRegister_input_2__.dout ;
  wire \__BoundaryScanRegister_input_2__.sout ;
  wire \__BoundaryScanRegister_input_3__.dout ;
  wire \__BoundaryScanRegister_input_3__.sout ;
  wire \__BoundaryScanRegister_input_4__.dout ;
  wire \__BoundaryScanRegister_input_4__.sout ;
  wire \__BoundaryScanRegister_input_5__.dout ;
  wire \__BoundaryScanRegister_input_5__.sout ;
  wire \__BoundaryScanRegister_input_6__.dout ;
  wire \__BoundaryScanRegister_input_6__.sout ;
  wire \__BoundaryScanRegister_input_7__.dout ;
  wire \__BoundaryScanRegister_input_7__.sout ;
  wire \__BoundaryScanRegister_input_8__.dout ;
  wire \__BoundaryScanRegister_input_8__.sout ;
  wire \__BoundaryScanRegister_output_10__.sin ;
  wire \__BoundaryScanRegister_output_10__.sout ;
  wire \__BoundaryScanRegister_output_11__.sout ;
  wire \__BoundaryScanRegister_output_12__.sout ;
  wire \__BoundaryScanRegister_output_13__.sout ;
  wire \__BoundaryScanRegister_output_14__.sout ;
  wire \__BoundaryScanRegister_output_15__.sout ;
  wire \__BoundaryScanRegister_output_16__.sout ;
  wire \__BoundaryScanRegister_output_9__.sin ;
  wire \__uuf__._000_ ;
  wire \__uuf__._001_ ;
  wire \__uuf__._002_ ;
  wire \__uuf__._003_ ;
  wire \__uuf__._004_ ;
  wire \__uuf__._005_ ;
  wire \__uuf__._006_ ;
  wire \__uuf__._007_ ;
  wire \__uuf__._008_ ;
  wire \__uuf__._009_ ;
  wire \__uuf__._010_ ;
  wire \__uuf__._011_ ;
  wire \__uuf__._012_ ;
  wire \__uuf__._013_ ;
  wire \__uuf__._014_ ;
  wire \__uuf__._015_ ;
  wire \__uuf__._016_ ;
  wire \__uuf__._017_ ;
  wire \__uuf__._018_ ;
  wire \__uuf__._019_ ;
  wire \__uuf__._020_ ;
  wire \__uuf__._021_ ;
  wire \__uuf__._022_ ;
  wire \__uuf__._023_ ;
  wire \__uuf__._024_ ;
  wire \__uuf__._025_ ;
  wire \__uuf__._026_ ;
  wire \__uuf__._027_ ;
  wire \__uuf__._028_ ;
  wire \__uuf__._029_ ;
  wire \__uuf__._030_ ;
  wire \__uuf__._031_ ;
  wire \__uuf__._032_ ;
  wire \__uuf__._033_ ;
  wire \__uuf__._034_ ;
  wire \__uuf__._035_ ;
  wire \__uuf__._036_ ;
  wire \__uuf__._037_ ;
  wire \__uuf__._038_ ;
  wire \__uuf__._039_ ;
  wire \__uuf__._040_ ;
  wire \__uuf__._041_ ;
  wire \__uuf__._042_ ;
  wire \__uuf__._043_ ;
  wire \__uuf__._044_ ;
  wire \__uuf__._045_ ;
  wire \__uuf__._046_ ;
  wire \__uuf__._047_ ;
  wire \__uuf__._048_ ;
  wire \__uuf__._049_ ;
  wire \__uuf__._050_ ;
  wire \__uuf__._051_ ;
  wire \__uuf__._052_ ;
  wire \__uuf__._053_ ;
  wire \__uuf__._054_ ;
  wire \__uuf__._055_ ;
  wire \__uuf__._056_ ;
  wire \__uuf__._057_ ;
  wire \__uuf__._058_ ;
  wire \__uuf__._059_ ;
  wire \__uuf__._060_ ;
  wire \__uuf__._061_ ;
  wire \__uuf__._062_ ;
  wire \__uuf__._063_ ;
  wire \__uuf__._064_ ;
  wire \__uuf__._065_ ;
  wire \__uuf__._066_ ;
  wire \__uuf__._067_ ;
  wire \__uuf__._068_ ;
  wire \__uuf__._069_ ;
  wire \__uuf__._070_ ;
  wire \__uuf__._071_ ;
  wire \__uuf__._072_ ;
  wire \__uuf__._073_ ;
  wire \__uuf__._074_ ;
  wire \__uuf__._075_ ;
  wire \__uuf__._076_ ;
  wire \__uuf__._077_ ;
  wire \__uuf__._078_ ;
  wire \__uuf__._079_ ;
  wire \__uuf__._080_ ;
  wire \__uuf__._081_ ;
  wire \__uuf__._082_ ;
  wire \__uuf__._083_ ;
  wire \__uuf__._084_ ;
  wire \__uuf__._085_ ;
  wire \__uuf__._086_ ;
  wire \__uuf__._087_ ;
  wire \__uuf__._088_ ;
  wire \__uuf__._089_ ;
  wire \__uuf__._090_ ;
  wire \__uuf__._091_ ;
  wire \__uuf__._092_ ;
  wire \__uuf__._093_ ;
  wire \__uuf__._094_ ;
  wire \__uuf__._095_ ;
  wire \__uuf__._096_ ;
  wire \__uuf__._097_ ;
  wire \__uuf__._098_ ;
  wire \__uuf__._099_ ;
  wire \__uuf__._100_ ;
  wire \__uuf__._101_ ;
  wire \__uuf__._102_ ;
  wire \__uuf__._103_ ;
  wire \__uuf__._104_ ;
  wire \__uuf__._105_ ;
  wire \__uuf__._106_ ;
  wire \__uuf__._107_ ;
  wire \__uuf__._108_ ;
  wire \__uuf__._109_ ;
  wire \__uuf__._110_ ;
  wire \__uuf__._111_ ;
  wire \__uuf__._112_ ;
  wire \__uuf__._113_ ;
  wire \__uuf__._114_ ;
  wire \__uuf__._115_ ;
  wire \__uuf__._116_ ;
  wire \__uuf__._117_ ;
  wire \__uuf__._118_ ;
  wire \__uuf__._119_ ;
  wire \__uuf__._120_ ;
  wire \__uuf__._121_ ;
  wire \__uuf__._122_ ;
  wire \__uuf__._123_ ;
  wire \__uuf__._124_ ;
  wire \__uuf__._125_ ;
  wire \__uuf__._126_ ;
  wire \__uuf__._127_ ;
  wire \__uuf__._128_ ;
  wire \__uuf__._129_ ;
  wire \__uuf__._130_ ;
  wire \__uuf__._131_ ;
  wire \__uuf__._132_ ;
  wire \__uuf__._133_ ;
  wire \__uuf__._134_ ;
  wire \__uuf__._135_ ;
  wire \__uuf__._136_ ;
  wire \__uuf__._137_ ;
  wire \__uuf__._138_ ;
  wire \__uuf__._139_ ;
  wire \__uuf__._140_ ;
  wire \__uuf__._141_ ;
  wire \__uuf__._142_ ;
  wire \__uuf__._143_ ;
  wire \__uuf__._144_ ;
  wire \__uuf__._145_ ;
  wire \__uuf__._146_ ;
  wire \__uuf__._147_ ;
  wire \__uuf__._148_ ;
  wire \__uuf__._149_ ;
  wire \__uuf__._150_ ;
  wire \__uuf__._151_ ;
  wire \__uuf__._152_ ;
  wire \__uuf__._153_ ;
  wire \__uuf__._154_ ;
  wire \__uuf__._155_ ;
  wire \__uuf__._156_ ;
  wire \__uuf__._157_ ;
  wire \__uuf__._158_ ;
  wire \__uuf__._159_ ;
  wire \__uuf__._160_ ;
  wire \__uuf__._161_ ;
  wire \__uuf__._162_ ;
  wire \__uuf__._163_ ;
  wire \__uuf__._164_ ;
  wire \__uuf__._165_ ;
  wire \__uuf__._166_ ;
  wire \__uuf__._167_ ;
  wire \__uuf__._168_ ;
  wire \__uuf__._169_ ;
  wire \__uuf__._170_ ;
  wire \__uuf__._171_ ;
  wire \__uuf__._172_ ;
  wire \__uuf__._173_ ;
  wire \__uuf__._174_ ;
  wire \__uuf__._175_ ;
  wire \__uuf__._176_ ;
  wire \__uuf__._177_ ;
  wire \__uuf__._178_ ;
  wire \__uuf__._179_ ;
  wire \__uuf__._180_ ;
  wire \__uuf__._181_ ;
  wire \__uuf__._182_ ;
  wire \__uuf__._183_ ;
  wire \__uuf__._184_ ;
  wire \__uuf__._185_ ;
  wire \__uuf__._186_ ;
  wire \__uuf__._187_ ;
  wire \__uuf__._188_ ;
  wire \__uuf__._189_ ;
  wire \__uuf__._190_ ;
  wire \__uuf__._191_ ;
  wire \__uuf__._192_ ;
  wire \__uuf__._193_ ;
  wire \__uuf__._194_ ;
  wire \__uuf__._195_ ;
  wire \__uuf__._196_ ;
  wire \__uuf__._197_ ;
  wire \__uuf__._198_ ;
  wire \__uuf__.control_module0.m0 ;
  wire \__uuf__.control_module0.next_state ;
  wire [7:0] \__uuf__.datapath_module0.multiplicand ;
  wire [3:0] \__uuf__.datapath_module0.multiplier ;
  input clk;
  output [7:0] product;
  output ready;
  input reset;
  input shift;
  input sin;
  output sout;
  input start;
  input tck;
  input test;
  input [3:0] word0;
  input [3:0] word1;
  NOT _137_ (
    .A(shift),
    .Y(_039_)
  );
  NOT _138_ (
    .A(test),
    .Y(_040_)
  );
  NAND _139_ (
    .A(\__BoundaryScanRegister_input_0__.sout ),
    .B(test),
    .Y(_041_)
  );
  NAND _140_ (
    .A(word0[0]),
    .B(_040_),
    .Y(_042_)
  );
  NAND _141_ (
    .A(_041_),
    .B(_042_),
    .Y(\__BoundaryScanRegister_input_0__.dout )
  );
  NAND _142_ (
    .A(sin),
    .B(shift),
    .Y(_043_)
  );
  NAND _143_ (
    .A(_039_),
    .B(\__BoundaryScanRegister_input_0__.dout ),
    .Y(_044_)
  );
  NAND _144_ (
    .A(_043_),
    .B(_044_),
    .Y(_000_)
  );
  NAND _145_ (
    .A(test),
    .B(\__BoundaryScanRegister_input_1__.sout ),
    .Y(_045_)
  );
  NAND _146_ (
    .A(_040_),
    .B(word0[1]),
    .Y(_046_)
  );
  NAND _147_ (
    .A(_045_),
    .B(_046_),
    .Y(\__BoundaryScanRegister_input_1__.dout )
  );
  NAND _148_ (
    .A(shift),
    .B(\__BoundaryScanRegister_input_0__.sout ),
    .Y(_047_)
  );
  NAND _149_ (
    .A(_039_),
    .B(\__BoundaryScanRegister_input_1__.dout ),
    .Y(_048_)
  );
  NAND _150_ (
    .A(_047_),
    .B(_048_),
    .Y(_001_)
  );
  NAND _151_ (
    .A(test),
    .B(\__BoundaryScanRegister_input_2__.sout ),
    .Y(_049_)
  );
  NAND _152_ (
    .A(_040_),
    .B(word0[2]),
    .Y(_050_)
  );
  NAND _153_ (
    .A(_049_),
    .B(_050_),
    .Y(\__BoundaryScanRegister_input_2__.dout )
  );
  NAND _154_ (
    .A(shift),
    .B(\__BoundaryScanRegister_input_1__.sout ),
    .Y(_051_)
  );
  NAND _155_ (
    .A(_039_),
    .B(\__BoundaryScanRegister_input_2__.dout ),
    .Y(_052_)
  );
  NAND _156_ (
    .A(_051_),
    .B(_052_),
    .Y(_002_)
  );
  NAND _157_ (
    .A(test),
    .B(\__BoundaryScanRegister_input_3__.sout ),
    .Y(_053_)
  );
  NAND _158_ (
    .A(_040_),
    .B(word0[3]),
    .Y(_054_)
  );
  NAND _159_ (
    .A(_053_),
    .B(_054_),
    .Y(\__BoundaryScanRegister_input_3__.dout )
  );
  NAND _160_ (
    .A(shift),
    .B(\__BoundaryScanRegister_input_2__.sout ),
    .Y(_055_)
  );
  NAND _161_ (
    .A(_039_),
    .B(\__BoundaryScanRegister_input_3__.dout ),
    .Y(_056_)
  );
  NAND _162_ (
    .A(_055_),
    .B(_056_),
    .Y(_003_)
  );
  NAND _163_ (
    .A(test),
    .B(\__BoundaryScanRegister_input_4__.sout ),
    .Y(_057_)
  );
  NAND _164_ (
    .A(_040_),
    .B(word1[0]),
    .Y(_058_)
  );
  NAND _165_ (
    .A(_057_),
    .B(_058_),
    .Y(\__BoundaryScanRegister_input_4__.dout )
  );
  NAND _166_ (
    .A(shift),
    .B(\__BoundaryScanRegister_input_3__.sout ),
    .Y(_059_)
  );
  NAND _167_ (
    .A(_039_),
    .B(\__BoundaryScanRegister_input_4__.dout ),
    .Y(_060_)
  );
  NAND _168_ (
    .A(_059_),
    .B(_060_),
    .Y(_004_)
  );
  NAND _169_ (
    .A(test),
    .B(\__BoundaryScanRegister_input_5__.sout ),
    .Y(_061_)
  );
  NAND _170_ (
    .A(_040_),
    .B(word1[1]),
    .Y(_062_)
  );
  NAND _171_ (
    .A(_061_),
    .B(_062_),
    .Y(\__BoundaryScanRegister_input_5__.dout )
  );
  NAND _172_ (
    .A(shift),
    .B(\__BoundaryScanRegister_input_4__.sout ),
    .Y(_063_)
  );
  NAND _173_ (
    .A(_039_),
    .B(\__BoundaryScanRegister_input_5__.dout ),
    .Y(_064_)
  );
  NAND _174_ (
    .A(_063_),
    .B(_064_),
    .Y(_005_)
  );
  NAND _175_ (
    .A(test),
    .B(\__BoundaryScanRegister_input_6__.sout ),
    .Y(_065_)
  );
  NAND _176_ (
    .A(_040_),
    .B(word1[2]),
    .Y(_066_)
  );
  NAND _177_ (
    .A(_065_),
    .B(_066_),
    .Y(\__BoundaryScanRegister_input_6__.dout )
  );
  NAND _178_ (
    .A(shift),
    .B(\__BoundaryScanRegister_input_5__.sout ),
    .Y(_067_)
  );
  NAND _179_ (
    .A(_039_),
    .B(\__BoundaryScanRegister_input_6__.dout ),
    .Y(_068_)
  );
  NAND _180_ (
    .A(_067_),
    .B(_068_),
    .Y(_006_)
  );
  NAND _181_ (
    .A(test),
    .B(\__BoundaryScanRegister_input_7__.sout ),
    .Y(_069_)
  );
  NAND _182_ (
    .A(_040_),
    .B(word1[3]),
    .Y(_070_)
  );
  NAND _183_ (
    .A(_069_),
    .B(_070_),
    .Y(\__BoundaryScanRegister_input_7__.dout )
  );
  NAND _184_ (
    .A(shift),
    .B(\__BoundaryScanRegister_input_6__.sout ),
    .Y(_071_)
  );
  NAND _185_ (
    .A(_039_),
    .B(\__BoundaryScanRegister_input_7__.dout ),
    .Y(_072_)
  );
  NAND _186_ (
    .A(_071_),
    .B(_072_),
    .Y(_007_)
  );
  NAND _187_ (
    .A(test),
    .B(\__BoundaryScanRegister_input_8__.sout ),
    .Y(_073_)
  );
  NAND _188_ (
    .A(_040_),
    .B(start),
    .Y(_074_)
  );
  NAND _189_ (
    .A(_073_),
    .B(_074_),
    .Y(\__BoundaryScanRegister_input_8__.dout )
  );
  NAND _190_ (
    .A(shift),
    .B(\__BoundaryScanRegister_input_7__.sout ),
    .Y(_075_)
  );
  NAND _191_ (
    .A(_039_),
    .B(\__BoundaryScanRegister_input_8__.dout ),
    .Y(_076_)
  );
  NAND _192_ (
    .A(_075_),
    .B(_076_),
    .Y(_008_)
  );
  NAND _193_ (
    .A(shift),
    .B(\__BoundaryScanRegister_output_10__.sin ),
    .Y(_077_)
  );
  NAND _194_ (
    .A(_039_),
    .B(product[1]),
    .Y(_078_)
  );
  NAND _195_ (
    .A(_077_),
    .B(_078_),
    .Y(_009_)
  );
  NAND _196_ (
    .A(shift),
    .B(\__BoundaryScanRegister_output_10__.sout ),
    .Y(_079_)
  );
  NAND _197_ (
    .A(_039_),
    .B(product[2]),
    .Y(_080_)
  );
  NAND _198_ (
    .A(_079_),
    .B(_080_),
    .Y(_010_)
  );
  NAND _199_ (
    .A(shift),
    .B(\__BoundaryScanRegister_output_11__.sout ),
    .Y(_081_)
  );
  NAND _200_ (
    .A(_039_),
    .B(product[3]),
    .Y(_082_)
  );
  NAND _201_ (
    .A(_081_),
    .B(_082_),
    .Y(_011_)
  );
  NAND _202_ (
    .A(shift),
    .B(\__BoundaryScanRegister_output_12__.sout ),
    .Y(_083_)
  );
  NAND _203_ (
    .A(_039_),
    .B(product[4]),
    .Y(_084_)
  );
  NAND _204_ (
    .A(_083_),
    .B(_084_),
    .Y(_012_)
  );
  NAND _205_ (
    .A(shift),
    .B(\__BoundaryScanRegister_output_13__.sout ),
    .Y(_085_)
  );
  NAND _206_ (
    .A(_039_),
    .B(product[5]),
    .Y(_086_)
  );
  NAND _207_ (
    .A(_085_),
    .B(_086_),
    .Y(_013_)
  );
  NAND _208_ (
    .A(shift),
    .B(\__BoundaryScanRegister_output_14__.sout ),
    .Y(_087_)
  );
  NAND _209_ (
    .A(_039_),
    .B(product[6]),
    .Y(_088_)
  );
  NAND _210_ (
    .A(_087_),
    .B(_088_),
    .Y(_014_)
  );
  NAND _211_ (
    .A(shift),
    .B(\__BoundaryScanRegister_output_15__.sout ),
    .Y(_089_)
  );
  NAND _212_ (
    .A(_039_),
    .B(product[7]),
    .Y(_090_)
  );
  NAND _213_ (
    .A(_089_),
    .B(_090_),
    .Y(_015_)
  );
  NAND _214_ (
    .A(shift),
    .B(\__BoundaryScanRegister_output_16__.sout ),
    .Y(_091_)
  );
  NAND _215_ (
    .A(_039_),
    .B(ready),
    .Y(_092_)
  );
  NAND _216_ (
    .A(_091_),
    .B(_092_),
    .Y(_016_)
  );
  NAND _217_ (
    .A(shift),
    .B(\__BoundaryScanRegister_output_9__.sin ),
    .Y(_093_)
  );
  NAND _218_ (
    .A(_039_),
    .B(product[0]),
    .Y(_094_)
  );
  NAND _219_ (
    .A(_093_),
    .B(_094_),
    .Y(_017_)
  );
  NAND _220_ (
    .A(shift),
    .B(\__BoundaryScanRegister_input_8__.sout ),
    .Y(_095_)
  );
  NAND _221_ (
    .A(_039_),
    .B(\__uuf__._012_ ),
    .Y(_096_)
  );
  NAND _222_ (
    .A(_095_),
    .B(_096_),
    .Y(_018_)
  );
  NAND _223_ (
    .A(shift),
    .B(product[0]),
    .Y(_097_)
  );
  NAND _224_ (
    .A(_039_),
    .B(\__uuf__._013_ ),
    .Y(_098_)
  );
  NAND _225_ (
    .A(_097_),
    .B(_098_),
    .Y(_019_)
  );
  NAND _226_ (
    .A(shift),
    .B(product[1]),
    .Y(_099_)
  );
  NAND _227_ (
    .A(_039_),
    .B(\__uuf__._014_ ),
    .Y(_100_)
  );
  NAND _228_ (
    .A(_099_),
    .B(_100_),
    .Y(_020_)
  );
  NAND _229_ (
    .A(shift),
    .B(product[2]),
    .Y(_101_)
  );
  NAND _230_ (
    .A(_039_),
    .B(\__uuf__._015_ ),
    .Y(_102_)
  );
  NAND _231_ (
    .A(_101_),
    .B(_102_),
    .Y(_021_)
  );
  NAND _232_ (
    .A(shift),
    .B(product[3]),
    .Y(_103_)
  );
  NAND _233_ (
    .A(_039_),
    .B(\__uuf__._016_ ),
    .Y(_104_)
  );
  NAND _234_ (
    .A(_103_),
    .B(_104_),
    .Y(_022_)
  );
  NAND _235_ (
    .A(shift),
    .B(product[4]),
    .Y(_105_)
  );
  NAND _236_ (
    .A(_039_),
    .B(\__uuf__._017_ ),
    .Y(_106_)
  );
  NAND _237_ (
    .A(_105_),
    .B(_106_),
    .Y(_023_)
  );
  NAND _238_ (
    .A(shift),
    .B(product[5]),
    .Y(_107_)
  );
  NAND _239_ (
    .A(_039_),
    .B(\__uuf__._018_ ),
    .Y(_108_)
  );
  NAND _240_ (
    .A(_107_),
    .B(_108_),
    .Y(_024_)
  );
  NAND _241_ (
    .A(shift),
    .B(product[6]),
    .Y(_109_)
  );
  NAND _242_ (
    .A(_039_),
    .B(\__uuf__._019_ ),
    .Y(_110_)
  );
  NAND _243_ (
    .A(_109_),
    .B(_110_),
    .Y(_025_)
  );
  NAND _244_ (
    .A(shift),
    .B(product[7]),
    .Y(_111_)
  );
  NAND _245_ (
    .A(_039_),
    .B(\__uuf__._008_ ),
    .Y(_112_)
  );
  NAND _246_ (
    .A(_111_),
    .B(_112_),
    .Y(_026_)
  );
  NAND _247_ (
    .A(shift),
    .B(\__uuf__.control_module0.m0 ),
    .Y(_113_)
  );
  NAND _248_ (
    .A(_039_),
    .B(\__uuf__._009_ ),
    .Y(_114_)
  );
  NAND _249_ (
    .A(_113_),
    .B(_114_),
    .Y(_027_)
  );
  NAND _250_ (
    .A(shift),
    .B(\__uuf__.datapath_module0.multiplier [1]),
    .Y(_115_)
  );
  NAND _251_ (
    .A(_039_),
    .B(\__uuf__._010_ ),
    .Y(_116_)
  );
  NAND _252_ (
    .A(_115_),
    .B(_116_),
    .Y(_028_)
  );
  NAND _253_ (
    .A(shift),
    .B(\__uuf__.datapath_module0.multiplier [2]),
    .Y(_117_)
  );
  NAND _254_ (
    .A(_039_),
    .B(\__uuf__._011_ ),
    .Y(_118_)
  );
  NAND _255_ (
    .A(_117_),
    .B(_118_),
    .Y(_029_)
  );
  NAND _256_ (
    .A(shift),
    .B(\__uuf__.datapath_module0.multiplier [3]),
    .Y(_119_)
  );
  NAND _257_ (
    .A(_039_),
    .B(\__uuf__._000_ ),
    .Y(_120_)
  );
  NAND _258_ (
    .A(_119_),
    .B(_120_),
    .Y(_030_)
  );
  NAND _259_ (
    .A(shift),
    .B(\__uuf__.datapath_module0.multiplicand [0]),
    .Y(_121_)
  );
  NAND _260_ (
    .A(_039_),
    .B(\__uuf__._001_ ),
    .Y(_122_)
  );
  NAND _261_ (
    .A(_121_),
    .B(_122_),
    .Y(_031_)
  );
  NAND _262_ (
    .A(shift),
    .B(\__uuf__.datapath_module0.multiplicand [1]),
    .Y(_123_)
  );
  NAND _263_ (
    .A(_039_),
    .B(\__uuf__._002_ ),
    .Y(_124_)
  );
  NAND _264_ (
    .A(_123_),
    .B(_124_),
    .Y(_032_)
  );
  NAND _265_ (
    .A(shift),
    .B(\__uuf__.datapath_module0.multiplicand [2]),
    .Y(_125_)
  );
  NAND _266_ (
    .A(_039_),
    .B(\__uuf__._003_ ),
    .Y(_126_)
  );
  NAND _267_ (
    .A(_125_),
    .B(_126_),
    .Y(_033_)
  );
  NAND _268_ (
    .A(shift),
    .B(\__uuf__.datapath_module0.multiplicand [3]),
    .Y(_127_)
  );
  NAND _269_ (
    .A(_039_),
    .B(\__uuf__._004_ ),
    .Y(_128_)
  );
  NAND _270_ (
    .A(_127_),
    .B(_128_),
    .Y(_034_)
  );
  NAND _271_ (
    .A(shift),
    .B(\__uuf__.datapath_module0.multiplicand [4]),
    .Y(_129_)
  );
  NAND _272_ (
    .A(_039_),
    .B(\__uuf__._005_ ),
    .Y(_130_)
  );
  NAND _273_ (
    .A(_129_),
    .B(_130_),
    .Y(_035_)
  );
  NAND _274_ (
    .A(shift),
    .B(\__uuf__.datapath_module0.multiplicand [5]),
    .Y(_131_)
  );
  NAND _275_ (
    .A(_039_),
    .B(\__uuf__._006_ ),
    .Y(_132_)
  );
  NAND _276_ (
    .A(_131_),
    .B(_132_),
    .Y(_036_)
  );
  NAND _277_ (
    .A(shift),
    .B(\__uuf__.datapath_module0.multiplicand [6]),
    .Y(_133_)
  );
  NAND _278_ (
    .A(_039_),
    .B(\__uuf__._007_ ),
    .Y(_134_)
  );
  NAND _279_ (
    .A(_133_),
    .B(_134_),
    .Y(_037_)
  );
  NAND _280_ (
    .A(shift),
    .B(\__uuf__.datapath_module0.multiplicand [7]),
    .Y(_135_)
  );
  NAND _281_ (
    .A(_039_),
    .B(\__uuf__.control_module0.next_state ),
    .Y(_136_)
  );
  NAND _282_ (
    .A(_135_),
    .B(_136_),
    .Y(_038_)
  );
  DFFSR _283_ (
    .C(tck),
    .D(_000_),
    .Q(\__BoundaryScanRegister_input_0__.sout ),
    .R(reset),
    .S(1'h0)
  );
  DFFSR _284_ (
    .C(tck),
    .D(_001_),
    .Q(\__BoundaryScanRegister_input_1__.sout ),
    .R(reset),
    .S(1'h0)
  );
  DFFSR _285_ (
    .C(tck),
    .D(_002_),
    .Q(\__BoundaryScanRegister_input_2__.sout ),
    .R(reset),
    .S(1'h0)
  );
  DFFSR _286_ (
    .C(tck),
    .D(_003_),
    .Q(\__BoundaryScanRegister_input_3__.sout ),
    .R(reset),
    .S(1'h0)
  );
  DFFSR _287_ (
    .C(tck),
    .D(_004_),
    .Q(\__BoundaryScanRegister_input_4__.sout ),
    .R(reset),
    .S(1'h0)
  );
  DFFSR _288_ (
    .C(tck),
    .D(_005_),
    .Q(\__BoundaryScanRegister_input_5__.sout ),
    .R(reset),
    .S(1'h0)
  );
  DFFSR _289_ (
    .C(tck),
    .D(_006_),
    .Q(\__BoundaryScanRegister_input_6__.sout ),
    .R(reset),
    .S(1'h0)
  );
  DFFSR _290_ (
    .C(tck),
    .D(_007_),
    .Q(\__BoundaryScanRegister_input_7__.sout ),
    .R(reset),
    .S(1'h0)
  );
  DFFSR _291_ (
    .C(tck),
    .D(_008_),
    .Q(\__BoundaryScanRegister_input_8__.sout ),
    .R(reset),
    .S(1'h0)
  );
  DFFSR _292_ (
    .C(tck),
    .D(_009_),
    .Q(\__BoundaryScanRegister_output_10__.sout ),
    .R(reset),
    .S(1'h0)
  );
  DFFSR _293_ (
    .C(tck),
    .D(_010_),
    .Q(\__BoundaryScanRegister_output_11__.sout ),
    .R(reset),
    .S(1'h0)
  );
  DFFSR _294_ (
    .C(tck),
    .D(_011_),
    .Q(\__BoundaryScanRegister_output_12__.sout ),
    .R(reset),
    .S(1'h0)
  );
  DFFSR _295_ (
    .C(tck),
    .D(_012_),
    .Q(\__BoundaryScanRegister_output_13__.sout ),
    .R(reset),
    .S(1'h0)
  );
  DFFSR _296_ (
    .C(tck),
    .D(_013_),
    .Q(\__BoundaryScanRegister_output_14__.sout ),
    .R(reset),
    .S(1'h0)
  );
  DFFSR _297_ (
    .C(tck),
    .D(_014_),
    .Q(\__BoundaryScanRegister_output_15__.sout ),
    .R(reset),
    .S(1'h0)
  );
  DFFSR _298_ (
    .C(tck),
    .D(_015_),
    .Q(\__BoundaryScanRegister_output_16__.sout ),
    .R(reset),
    .S(1'h0)
  );
  DFFSR _299_ (
    .C(tck),
    .D(_016_),
    .Q(sout),
    .R(reset),
    .S(1'h0)
  );
  DFFSR _300_ (
    .C(tck),
    .D(_017_),
    .Q(\__BoundaryScanRegister_output_10__.sin ),
    .R(reset),
    .S(1'h0)
  );
  NOT \__uuf__._199_  (
    .A(\__uuf__.datapath_module0.multiplier [3]),
    .Y(\__uuf__._155_ )
  );
  NOT \__uuf__._200_  (
    .A(\__uuf__.datapath_module0.multiplier [2]),
    .Y(\__uuf__._156_ )
  );
  NOT \__uuf__._201_  (
    .A(\__BoundaryScanRegister_input_8__.dout ),
    .Y(\__uuf__._157_ )
  );
  NOT \__uuf__._202_  (
    .A(\__BoundaryScanRegister_output_9__.sin ),
    .Y(\__uuf__._158_ )
  );
  NOT \__uuf__._203_  (
    .A(product[0]),
    .Y(\__uuf__._159_ )
  );
  NOT \__uuf__._204_  (
    .A(\__uuf__.control_module0.m0 ),
    .Y(\__uuf__._160_ )
  );
  NOT \__uuf__._205_  (
    .A(\__uuf__.datapath_module0.multiplicand [0]),
    .Y(\__uuf__._161_ )
  );
  NOT \__uuf__._206_  (
    .A(product[2]),
    .Y(\__uuf__._162_ )
  );
  NOT \__uuf__._207_  (
    .A(product[3]),
    .Y(\__uuf__._163_ )
  );
  NOT \__uuf__._208_  (
    .A(\__uuf__.datapath_module0.multiplicand [3]),
    .Y(\__uuf__._164_ )
  );
  NOT \__uuf__._209_  (
    .A(product[4]),
    .Y(\__uuf__._165_ )
  );
  NOT \__uuf__._210_  (
    .A(\__uuf__.datapath_module0.multiplicand [4]),
    .Y(\__uuf__._166_ )
  );
  NOT \__uuf__._211_  (
    .A(product[5]),
    .Y(\__uuf__._167_ )
  );
  NOT \__uuf__._212_  (
    .A(\__uuf__.datapath_module0.multiplicand [5]),
    .Y(\__uuf__._168_ )
  );
  NOT \__uuf__._213_  (
    .A(product[6]),
    .Y(\__uuf__._169_ )
  );
  NOT \__uuf__._214_  (
    .A(\__uuf__.datapath_module0.multiplicand [6]),
    .Y(\__uuf__._170_ )
  );
  NOT \__uuf__._215_  (
    .A(\__uuf__.datapath_module0.multiplicand [7]),
    .Y(\__uuf__._171_ )
  );
  NOR \__uuf__._216_  (
    .A(\__BoundaryScanRegister_input_1__.dout ),
    .B(\__BoundaryScanRegister_input_0__.dout ),
    .Y(\__uuf__._172_ )
  );
  NOR \__uuf__._217_  (
    .A(\__BoundaryScanRegister_input_3__.dout ),
    .B(\__BoundaryScanRegister_input_2__.dout ),
    .Y(\__uuf__._173_ )
  );
  NAND \__uuf__._218_  (
    .A(\__uuf__._172_ ),
    .B(\__uuf__._173_ ),
    .Y(\__uuf__._174_ )
  );
  NOR \__uuf__._219_  (
    .A(\__BoundaryScanRegister_input_7__.dout ),
    .B(\__BoundaryScanRegister_input_6__.dout ),
    .Y(\__uuf__._175_ )
  );
  NOR \__uuf__._220_  (
    .A(\__BoundaryScanRegister_input_5__.dout ),
    .B(\__BoundaryScanRegister_input_4__.dout ),
    .Y(\__uuf__._176_ )
  );
  NAND \__uuf__._221_  (
    .A(\__uuf__._175_ ),
    .B(\__uuf__._176_ ),
    .Y(\__uuf__._177_ )
  );
  NAND \__uuf__._222_  (
    .A(\__uuf__._174_ ),
    .B(\__uuf__._177_ ),
    .Y(\__uuf__._178_ )
  );
  NOT \__uuf__._223_  (
    .A(\__uuf__._178_ ),
    .Y(\__uuf__._179_ )
  );
  NOR \__uuf__._224_  (
    .A(reset),
    .B(\__BoundaryScanRegister_output_9__.sin ),
    .Y(ready)
  );
  NOT \__uuf__._225_  (
    .A(ready),
    .Y(\__uuf__._180_ )
  );
  NOR \__uuf__._226_  (
    .A(\__uuf__._157_ ),
    .B(\__uuf__._180_ ),
    .Y(\__uuf__._181_ )
  );
  NAND \__uuf__._227_  (
    .A(\__BoundaryScanRegister_input_8__.dout ),
    .B(ready),
    .Y(\__uuf__._182_ )
  );
  NOR \__uuf__._228_  (
    .A(\__uuf__._178_ ),
    .B(\__uuf__._182_ ),
    .Y(\__uuf__._183_ )
  );
  NAND \__uuf__._229_  (
    .A(\__uuf__._179_ ),
    .B(\__uuf__._181_ ),
    .Y(\__uuf__._184_ )
  );
  NAND \__uuf__._230_  (
    .A(\__uuf__.datapath_module0.multiplier [3]),
    .B(\__BoundaryScanRegister_output_9__.sin ),
    .Y(\__uuf__._185_ )
  );
  NOT \__uuf__._231_  (
    .A(\__uuf__._185_ ),
    .Y(\__uuf__._186_ )
  );
  NOR \__uuf__._232_  (
    .A(\__uuf__._183_ ),
    .B(\__uuf__._186_ ),
    .Y(\__uuf__._187_ )
  );
  NAND \__uuf__._233_  (
    .A(\__uuf__._184_ ),
    .B(\__uuf__._185_ ),
    .Y(\__uuf__._188_ )
  );
  NOR \__uuf__._234_  (
    .A(\__uuf__._160_ ),
    .B(\__uuf__.datapath_module0.multiplier [1]),
    .Y(\__uuf__._189_ )
  );
  NAND \__uuf__._235_  (
    .A(\__uuf__._156_ ),
    .B(\__uuf__._189_ ),
    .Y(\__uuf__._190_ )
  );
  NAND \__uuf__._236_  (
    .A(\__BoundaryScanRegister_output_9__.sin ),
    .B(\__uuf__._190_ ),
    .Y(\__uuf__._191_ )
  );
  NAND \__uuf__._237_  (
    .A(\__uuf__._187_ ),
    .B(\__uuf__._191_ ),
    .Y(\__uuf__.control_module0.next_state )
  );
  NAND \__uuf__._238_  (
    .A(\__uuf__._178_ ),
    .B(\__uuf__._181_ ),
    .Y(\__uuf__._192_ )
  );
  NOT \__uuf__._239_  (
    .A(\__uuf__._192_ ),
    .Y(\__uuf__._193_ )
  );
  NAND \__uuf__._240_  (
    .A(\__BoundaryScanRegister_output_9__.sin ),
    .B(\__uuf__.datapath_module0.multiplicand [0]),
    .Y(\__uuf__._194_ )
  );
  NOT \__uuf__._241_  (
    .A(\__uuf__._194_ ),
    .Y(\__uuf__._195_ )
  );
  NOR \__uuf__._242_  (
    .A(\__uuf__._160_ ),
    .B(\__uuf__._194_ ),
    .Y(\__uuf__._196_ )
  );
  NAND \__uuf__._243_  (
    .A(\__uuf__.control_module0.m0 ),
    .B(\__uuf__._195_ ),
    .Y(\__uuf__._197_ )
  );
  NAND \__uuf__._244_  (
    .A(product[0]),
    .B(\__uuf__._196_ ),
    .Y(\__uuf__._198_ )
  );
  NAND \__uuf__._245_  (
    .A(\__uuf__._159_ ),
    .B(\__uuf__._197_ ),
    .Y(\__uuf__._020_ )
  );
  NAND \__uuf__._246_  (
    .A(\__uuf__._198_ ),
    .B(\__uuf__._020_ ),
    .Y(\__uuf__._021_ )
  );
  NOR \__uuf__._247_  (
    .A(\__uuf__._193_ ),
    .B(\__uuf__._021_ ),
    .Y(\__uuf__._012_ )
  );
  NAND \__uuf__._248_  (
    .A(\__BoundaryScanRegister_output_9__.sin ),
    .B(\__uuf__.control_module0.m0 ),
    .Y(\__uuf__._022_ )
  );
  NOT \__uuf__._249_  (
    .A(\__uuf__._022_ ),
    .Y(\__uuf__._023_ )
  );
  NAND \__uuf__._250_  (
    .A(product[0]),
    .B(\__uuf__.datapath_module0.multiplicand [0]),
    .Y(\__uuf__._024_ )
  );
  NOT \__uuf__._251_  (
    .A(\__uuf__._024_ ),
    .Y(\__uuf__._025_ )
  );
  NOR \__uuf__._252_  (
    .A(product[1]),
    .B(\__uuf__.datapath_module0.multiplicand [1]),
    .Y(\__uuf__._026_ )
  );
  NOT \__uuf__._253_  (
    .A(\__uuf__._026_ ),
    .Y(\__uuf__._027_ )
  );
  NAND \__uuf__._254_  (
    .A(product[1]),
    .B(\__uuf__.datapath_module0.multiplicand [1]),
    .Y(\__uuf__._028_ )
  );
  NOT \__uuf__._255_  (
    .A(\__uuf__._028_ ),
    .Y(\__uuf__._029_ )
  );
  NOR \__uuf__._256_  (
    .A(\__uuf__._026_ ),
    .B(\__uuf__._029_ ),
    .Y(\__uuf__._030_ )
  );
  NAND \__uuf__._257_  (
    .A(\__uuf__._027_ ),
    .B(\__uuf__._028_ ),
    .Y(\__uuf__._031_ )
  );
  NAND \__uuf__._258_  (
    .A(\__uuf__._025_ ),
    .B(\__uuf__._030_ ),
    .Y(\__uuf__._032_ )
  );
  NAND \__uuf__._259_  (
    .A(\__uuf__._024_ ),
    .B(\__uuf__._031_ ),
    .Y(\__uuf__._033_ )
  );
  NAND \__uuf__._260_  (
    .A(\__uuf__._032_ ),
    .B(\__uuf__._033_ ),
    .Y(\__uuf__._034_ )
  );
  NAND \__uuf__._261_  (
    .A(\__uuf__._023_ ),
    .B(\__uuf__._034_ ),
    .Y(\__uuf__._035_ )
  );
  NOR \__uuf__._262_  (
    .A(product[1]),
    .B(\__uuf__._023_ ),
    .Y(\__uuf__._036_ )
  );
  NAND \__uuf__._263_  (
    .A(\__uuf__._192_ ),
    .B(\__uuf__._035_ ),
    .Y(\__uuf__._037_ )
  );
  NOR \__uuf__._264_  (
    .A(\__uuf__._036_ ),
    .B(\__uuf__._037_ ),
    .Y(\__uuf__._013_ )
  );
  NAND \__uuf__._265_  (
    .A(\__uuf__._028_ ),
    .B(\__uuf__._032_ ),
    .Y(\__uuf__._038_ )
  );
  NAND \__uuf__._266_  (
    .A(product[2]),
    .B(\__uuf__.datapath_module0.multiplicand [2]),
    .Y(\__uuf__._039_ )
  );
  NOT \__uuf__._267_  (
    .A(\__uuf__._039_ ),
    .Y(\__uuf__._040_ )
  );
  NOR \__uuf__._268_  (
    .A(product[2]),
    .B(\__uuf__.datapath_module0.multiplicand [2]),
    .Y(\__uuf__._041_ )
  );
  NOR \__uuf__._269_  (
    .A(\__uuf__._040_ ),
    .B(\__uuf__._041_ ),
    .Y(\__uuf__._042_ )
  );
  NOR \__uuf__._270_  (
    .A(\__uuf__._038_ ),
    .B(\__uuf__._042_ ),
    .Y(\__uuf__._043_ )
  );
  NAND \__uuf__._271_  (
    .A(\__uuf__._038_ ),
    .B(\__uuf__._042_ ),
    .Y(\__uuf__._044_ )
  );
  NOT \__uuf__._272_  (
    .A(\__uuf__._044_ ),
    .Y(\__uuf__._045_ )
  );
  NOR \__uuf__._273_  (
    .A(\__uuf__._043_ ),
    .B(\__uuf__._045_ ),
    .Y(\__uuf__._046_ )
  );
  NOR \__uuf__._274_  (
    .A(\__uuf__._022_ ),
    .B(\__uuf__._046_ ),
    .Y(\__uuf__._047_ )
  );
  NAND \__uuf__._275_  (
    .A(\__uuf__._162_ ),
    .B(\__uuf__._022_ ),
    .Y(\__uuf__._048_ )
  );
  NAND \__uuf__._276_  (
    .A(\__uuf__._192_ ),
    .B(\__uuf__._048_ ),
    .Y(\__uuf__._049_ )
  );
  NOR \__uuf__._277_  (
    .A(\__uuf__._047_ ),
    .B(\__uuf__._049_ ),
    .Y(\__uuf__._014_ )
  );
  NAND \__uuf__._278_  (
    .A(\__uuf__._039_ ),
    .B(\__uuf__._044_ ),
    .Y(\__uuf__._050_ )
  );
  NAND \__uuf__._279_  (
    .A(\__uuf__._163_ ),
    .B(\__uuf__._164_ ),
    .Y(\__uuf__._051_ )
  );
  NAND \__uuf__._280_  (
    .A(product[3]),
    .B(\__uuf__.datapath_module0.multiplicand [3]),
    .Y(\__uuf__._052_ )
  );
  NAND \__uuf__._281_  (
    .A(\__uuf__._051_ ),
    .B(\__uuf__._052_ ),
    .Y(\__uuf__._053_ )
  );
  NAND \__uuf__._282_  (
    .A(\__uuf__._050_ ),
    .B(\__uuf__._053_ ),
    .Y(\__uuf__._054_ )
  );
  NOR \__uuf__._283_  (
    .A(\__uuf__._050_ ),
    .B(\__uuf__._053_ ),
    .Y(\__uuf__._055_ )
  );
  NOT \__uuf__._284_  (
    .A(\__uuf__._055_ ),
    .Y(\__uuf__._056_ )
  );
  NAND \__uuf__._285_  (
    .A(\__uuf__._054_ ),
    .B(\__uuf__._056_ ),
    .Y(\__uuf__._057_ )
  );
  NOR \__uuf__._286_  (
    .A(\__uuf__._022_ ),
    .B(\__uuf__._057_ ),
    .Y(\__uuf__._058_ )
  );
  NAND \__uuf__._287_  (
    .A(\__uuf__._163_ ),
    .B(\__uuf__._022_ ),
    .Y(\__uuf__._059_ )
  );
  NAND \__uuf__._288_  (
    .A(\__uuf__._192_ ),
    .B(\__uuf__._059_ ),
    .Y(\__uuf__._060_ )
  );
  NOR \__uuf__._289_  (
    .A(\__uuf__._058_ ),
    .B(\__uuf__._060_ ),
    .Y(\__uuf__._015_ )
  );
  NOR \__uuf__._290_  (
    .A(product[4]),
    .B(\__uuf__.datapath_module0.multiplicand [4]),
    .Y(\__uuf__._061_ )
  );
  NAND \__uuf__._291_  (
    .A(product[4]),
    .B(\__uuf__.datapath_module0.multiplicand [4]),
    .Y(\__uuf__._062_ )
  );
  NOT \__uuf__._292_  (
    .A(\__uuf__._062_ ),
    .Y(\__uuf__._063_ )
  );
  NOR \__uuf__._293_  (
    .A(\__uuf__._061_ ),
    .B(\__uuf__._063_ ),
    .Y(\__uuf__._064_ )
  );
  NAND \__uuf__._294_  (
    .A(\__uuf__._050_ ),
    .B(\__uuf__._051_ ),
    .Y(\__uuf__._065_ )
  );
  NAND \__uuf__._295_  (
    .A(\__uuf__._052_ ),
    .B(\__uuf__._065_ ),
    .Y(\__uuf__._066_ )
  );
  NAND \__uuf__._296_  (
    .A(\__uuf__._064_ ),
    .B(\__uuf__._066_ ),
    .Y(\__uuf__._067_ )
  );
  NOT \__uuf__._297_  (
    .A(\__uuf__._067_ ),
    .Y(\__uuf__._068_ )
  );
  NOR \__uuf__._298_  (
    .A(\__uuf__._064_ ),
    .B(\__uuf__._066_ ),
    .Y(\__uuf__._069_ )
  );
  NOR \__uuf__._299_  (
    .A(\__uuf__._068_ ),
    .B(\__uuf__._069_ ),
    .Y(\__uuf__._070_ )
  );
  NOR \__uuf__._300_  (
    .A(\__uuf__._022_ ),
    .B(\__uuf__._070_ ),
    .Y(\__uuf__._071_ )
  );
  NAND \__uuf__._301_  (
    .A(\__uuf__._165_ ),
    .B(\__uuf__._022_ ),
    .Y(\__uuf__._072_ )
  );
  NAND \__uuf__._302_  (
    .A(\__uuf__._192_ ),
    .B(\__uuf__._072_ ),
    .Y(\__uuf__._073_ )
  );
  NOR \__uuf__._303_  (
    .A(\__uuf__._071_ ),
    .B(\__uuf__._073_ ),
    .Y(\__uuf__._016_ )
  );
  NAND \__uuf__._304_  (
    .A(\__uuf__._062_ ),
    .B(\__uuf__._067_ ),
    .Y(\__uuf__._074_ )
  );
  NOR \__uuf__._305_  (
    .A(product[5]),
    .B(\__uuf__.datapath_module0.multiplicand [5]),
    .Y(\__uuf__._075_ )
  );
  NAND \__uuf__._306_  (
    .A(product[5]),
    .B(\__uuf__.datapath_module0.multiplicand [5]),
    .Y(\__uuf__._076_ )
  );
  NOT \__uuf__._307_  (
    .A(\__uuf__._076_ ),
    .Y(\__uuf__._077_ )
  );
  NOR \__uuf__._308_  (
    .A(\__uuf__._075_ ),
    .B(\__uuf__._077_ ),
    .Y(\__uuf__._078_ )
  );
  NAND \__uuf__._309_  (
    .A(\__uuf__._074_ ),
    .B(\__uuf__._078_ ),
    .Y(\__uuf__._079_ )
  );
  NOT \__uuf__._310_  (
    .A(\__uuf__._079_ ),
    .Y(\__uuf__._080_ )
  );
  NOR \__uuf__._311_  (
    .A(\__uuf__._074_ ),
    .B(\__uuf__._078_ ),
    .Y(\__uuf__._081_ )
  );
  NOR \__uuf__._312_  (
    .A(\__uuf__._080_ ),
    .B(\__uuf__._081_ ),
    .Y(\__uuf__._082_ )
  );
  NOR \__uuf__._313_  (
    .A(\__uuf__._022_ ),
    .B(\__uuf__._082_ ),
    .Y(\__uuf__._083_ )
  );
  NAND \__uuf__._314_  (
    .A(\__uuf__._167_ ),
    .B(\__uuf__._022_ ),
    .Y(\__uuf__._084_ )
  );
  NAND \__uuf__._315_  (
    .A(\__uuf__._192_ ),
    .B(\__uuf__._084_ ),
    .Y(\__uuf__._085_ )
  );
  NOR \__uuf__._316_  (
    .A(\__uuf__._083_ ),
    .B(\__uuf__._085_ ),
    .Y(\__uuf__._017_ )
  );
  NAND \__uuf__._317_  (
    .A(\__uuf__._076_ ),
    .B(\__uuf__._079_ ),
    .Y(\__uuf__._086_ )
  );
  NAND \__uuf__._318_  (
    .A(product[6]),
    .B(\__uuf__.datapath_module0.multiplicand [6]),
    .Y(\__uuf__._087_ )
  );
  NOT \__uuf__._319_  (
    .A(\__uuf__._087_ ),
    .Y(\__uuf__._088_ )
  );
  NOR \__uuf__._320_  (
    .A(product[6]),
    .B(\__uuf__.datapath_module0.multiplicand [6]),
    .Y(\__uuf__._089_ )
  );
  NOR \__uuf__._321_  (
    .A(\__uuf__._088_ ),
    .B(\__uuf__._089_ ),
    .Y(\__uuf__._090_ )
  );
  NOR \__uuf__._322_  (
    .A(\__uuf__._086_ ),
    .B(\__uuf__._090_ ),
    .Y(\__uuf__._091_ )
  );
  NAND \__uuf__._323_  (
    .A(\__uuf__._086_ ),
    .B(\__uuf__._090_ ),
    .Y(\__uuf__._092_ )
  );
  NOT \__uuf__._324_  (
    .A(\__uuf__._092_ ),
    .Y(\__uuf__._093_ )
  );
  NOR \__uuf__._325_  (
    .A(\__uuf__._091_ ),
    .B(\__uuf__._093_ ),
    .Y(\__uuf__._094_ )
  );
  NOR \__uuf__._326_  (
    .A(\__uuf__._022_ ),
    .B(\__uuf__._094_ ),
    .Y(\__uuf__._095_ )
  );
  NAND \__uuf__._327_  (
    .A(\__uuf__._169_ ),
    .B(\__uuf__._022_ ),
    .Y(\__uuf__._096_ )
  );
  NAND \__uuf__._328_  (
    .A(\__uuf__._192_ ),
    .B(\__uuf__._096_ ),
    .Y(\__uuf__._097_ )
  );
  NOR \__uuf__._329_  (
    .A(\__uuf__._095_ ),
    .B(\__uuf__._097_ ),
    .Y(\__uuf__._018_ )
  );
  NAND \__uuf__._330_  (
    .A(\__uuf__._087_ ),
    .B(\__uuf__._092_ ),
    .Y(\__uuf__._098_ )
  );
  NAND \__uuf__._331_  (
    .A(\__uuf__.datapath_module0.multiplicand [7]),
    .B(\__uuf__._098_ ),
    .Y(\__uuf__._099_ )
  );
  NOR \__uuf__._332_  (
    .A(\__uuf__.datapath_module0.multiplicand [7]),
    .B(\__uuf__._098_ ),
    .Y(\__uuf__._100_ )
  );
  NAND \__uuf__._333_  (
    .A(\__uuf__._023_ ),
    .B(\__uuf__._099_ ),
    .Y(\__uuf__._101_ )
  );
  NOR \__uuf__._334_  (
    .A(\__uuf__._100_ ),
    .B(\__uuf__._101_ ),
    .Y(\__uuf__._102_ )
  );
  NAND \__uuf__._335_  (
    .A(product[7]),
    .B(\__uuf__._102_ ),
    .Y(\__uuf__._103_ )
  );
  NOR \__uuf__._336_  (
    .A(product[7]),
    .B(\__uuf__._102_ ),
    .Y(\__uuf__._104_ )
  );
  NAND \__uuf__._337_  (
    .A(\__uuf__._192_ ),
    .B(\__uuf__._103_ ),
    .Y(\__uuf__._105_ )
  );
  NOR \__uuf__._338_  (
    .A(\__uuf__._104_ ),
    .B(\__uuf__._105_ ),
    .Y(\__uuf__._019_ )
  );
  NOR \__uuf__._339_  (
    .A(\__BoundaryScanRegister_output_9__.sin ),
    .B(\__uuf__._161_ ),
    .Y(\__uuf__._106_ )
  );
  NOR \__uuf__._340_  (
    .A(\__uuf__._183_ ),
    .B(\__uuf__._106_ ),
    .Y(\__uuf__._107_ )
  );
  NOR \__uuf__._341_  (
    .A(\__BoundaryScanRegister_input_0__.dout ),
    .B(\__uuf__._184_ ),
    .Y(\__uuf__._108_ )
  );
  NOR \__uuf__._342_  (
    .A(\__uuf__._107_ ),
    .B(\__uuf__._108_ ),
    .Y(\__uuf__._000_ )
  );
  NAND \__uuf__._343_  (
    .A(\__uuf__._158_ ),
    .B(\__uuf__.datapath_module0.multiplicand [1]),
    .Y(\__uuf__._109_ )
  );
  NAND \__uuf__._344_  (
    .A(\__uuf__._194_ ),
    .B(\__uuf__._109_ ),
    .Y(\__uuf__._110_ )
  );
  NAND \__uuf__._345_  (
    .A(\__uuf__._184_ ),
    .B(\__uuf__._110_ ),
    .Y(\__uuf__._111_ )
  );
  NAND \__uuf__._346_  (
    .A(\__BoundaryScanRegister_input_1__.dout ),
    .B(\__uuf__._183_ ),
    .Y(\__uuf__._112_ )
  );
  NAND \__uuf__._347_  (
    .A(\__uuf__._111_ ),
    .B(\__uuf__._112_ ),
    .Y(\__uuf__._001_ )
  );
  NAND \__uuf__._348_  (
    .A(\__uuf__._158_ ),
    .B(\__uuf__.datapath_module0.multiplicand [2]),
    .Y(\__uuf__._113_ )
  );
  NAND \__uuf__._349_  (
    .A(\__BoundaryScanRegister_output_9__.sin ),
    .B(\__uuf__.datapath_module0.multiplicand [1]),
    .Y(\__uuf__._114_ )
  );
  NAND \__uuf__._350_  (
    .A(\__uuf__._113_ ),
    .B(\__uuf__._114_ ),
    .Y(\__uuf__._115_ )
  );
  NAND \__uuf__._351_  (
    .A(\__uuf__._184_ ),
    .B(\__uuf__._115_ ),
    .Y(\__uuf__._116_ )
  );
  NAND \__uuf__._352_  (
    .A(\__BoundaryScanRegister_input_2__.dout ),
    .B(\__uuf__._183_ ),
    .Y(\__uuf__._117_ )
  );
  NAND \__uuf__._353_  (
    .A(\__uuf__._116_ ),
    .B(\__uuf__._117_ ),
    .Y(\__uuf__._002_ )
  );
  NAND \__uuf__._354_  (
    .A(\__uuf__._158_ ),
    .B(\__uuf__.datapath_module0.multiplicand [3]),
    .Y(\__uuf__._118_ )
  );
  NAND \__uuf__._355_  (
    .A(\__BoundaryScanRegister_output_9__.sin ),
    .B(\__uuf__.datapath_module0.multiplicand [2]),
    .Y(\__uuf__._119_ )
  );
  NAND \__uuf__._356_  (
    .A(\__uuf__._118_ ),
    .B(\__uuf__._119_ ),
    .Y(\__uuf__._120_ )
  );
  NAND \__uuf__._357_  (
    .A(\__uuf__._184_ ),
    .B(\__uuf__._120_ ),
    .Y(\__uuf__._121_ )
  );
  NAND \__uuf__._358_  (
    .A(\__BoundaryScanRegister_input_3__.dout ),
    .B(\__uuf__._183_ ),
    .Y(\__uuf__._122_ )
  );
  NAND \__uuf__._359_  (
    .A(\__uuf__._121_ ),
    .B(\__uuf__._122_ ),
    .Y(\__uuf__._003_ )
  );
  NOR \__uuf__._360_  (
    .A(\__BoundaryScanRegister_output_9__.sin ),
    .B(\__uuf__._166_ ),
    .Y(\__uuf__._123_ )
  );
  NAND \__uuf__._361_  (
    .A(\__BoundaryScanRegister_output_9__.sin ),
    .B(\__uuf__.datapath_module0.multiplicand [3]),
    .Y(\__uuf__._124_ )
  );
  NOT \__uuf__._362_  (
    .A(\__uuf__._124_ ),
    .Y(\__uuf__._125_ )
  );
  NOR \__uuf__._363_  (
    .A(\__uuf__._123_ ),
    .B(\__uuf__._125_ ),
    .Y(\__uuf__._126_ )
  );
  NOR \__uuf__._364_  (
    .A(\__uuf__._183_ ),
    .B(\__uuf__._126_ ),
    .Y(\__uuf__._004_ )
  );
  NOR \__uuf__._365_  (
    .A(\__BoundaryScanRegister_output_9__.sin ),
    .B(\__uuf__._168_ ),
    .Y(\__uuf__._127_ )
  );
  NAND \__uuf__._366_  (
    .A(\__BoundaryScanRegister_output_9__.sin ),
    .B(\__uuf__.datapath_module0.multiplicand [4]),
    .Y(\__uuf__._128_ )
  );
  NOT \__uuf__._367_  (
    .A(\__uuf__._128_ ),
    .Y(\__uuf__._129_ )
  );
  NOR \__uuf__._368_  (
    .A(\__uuf__._127_ ),
    .B(\__uuf__._129_ ),
    .Y(\__uuf__._130_ )
  );
  NOR \__uuf__._369_  (
    .A(\__uuf__._183_ ),
    .B(\__uuf__._130_ ),
    .Y(\__uuf__._005_ )
  );
  NOR \__uuf__._370_  (
    .A(\__BoundaryScanRegister_output_9__.sin ),
    .B(\__uuf__._170_ ),
    .Y(\__uuf__._131_ )
  );
  NAND \__uuf__._371_  (
    .A(\__BoundaryScanRegister_output_9__.sin ),
    .B(\__uuf__.datapath_module0.multiplicand [5]),
    .Y(\__uuf__._132_ )
  );
  NOT \__uuf__._372_  (
    .A(\__uuf__._132_ ),
    .Y(\__uuf__._133_ )
  );
  NOR \__uuf__._373_  (
    .A(\__uuf__._131_ ),
    .B(\__uuf__._133_ ),
    .Y(\__uuf__._134_ )
  );
  NOR \__uuf__._374_  (
    .A(\__uuf__._183_ ),
    .B(\__uuf__._134_ ),
    .Y(\__uuf__._006_ )
  );
  NOR \__uuf__._375_  (
    .A(\__BoundaryScanRegister_output_9__.sin ),
    .B(\__uuf__._171_ ),
    .Y(\__uuf__._135_ )
  );
  NAND \__uuf__._376_  (
    .A(\__BoundaryScanRegister_output_9__.sin ),
    .B(\__uuf__.datapath_module0.multiplicand [6]),
    .Y(\__uuf__._136_ )
  );
  NOT \__uuf__._377_  (
    .A(\__uuf__._136_ ),
    .Y(\__uuf__._137_ )
  );
  NOR \__uuf__._378_  (
    .A(\__uuf__._135_ ),
    .B(\__uuf__._137_ ),
    .Y(\__uuf__._138_ )
  );
  NOR \__uuf__._379_  (
    .A(\__uuf__._183_ ),
    .B(\__uuf__._138_ ),
    .Y(\__uuf__._007_ )
  );
  NAND \__uuf__._380_  (
    .A(\__uuf__._158_ ),
    .B(\__uuf__.control_module0.m0 ),
    .Y(\__uuf__._139_ )
  );
  NAND \__uuf__._381_  (
    .A(\__BoundaryScanRegister_output_9__.sin ),
    .B(\__uuf__.datapath_module0.multiplier [1]),
    .Y(\__uuf__._140_ )
  );
  NAND \__uuf__._382_  (
    .A(\__uuf__._139_ ),
    .B(\__uuf__._140_ ),
    .Y(\__uuf__._141_ )
  );
  NAND \__uuf__._383_  (
    .A(\__uuf__._184_ ),
    .B(\__uuf__._141_ ),
    .Y(\__uuf__._142_ )
  );
  NAND \__uuf__._384_  (
    .A(\__BoundaryScanRegister_input_4__.dout ),
    .B(\__uuf__._183_ ),
    .Y(\__uuf__._143_ )
  );
  NAND \__uuf__._385_  (
    .A(\__uuf__._142_ ),
    .B(\__uuf__._143_ ),
    .Y(\__uuf__._008_ )
  );
  NAND \__uuf__._386_  (
    .A(\__uuf__._158_ ),
    .B(\__uuf__.datapath_module0.multiplier [1]),
    .Y(\__uuf__._144_ )
  );
  NAND \__uuf__._387_  (
    .A(\__uuf__.datapath_module0.multiplier [2]),
    .B(\__BoundaryScanRegister_output_9__.sin ),
    .Y(\__uuf__._145_ )
  );
  NAND \__uuf__._388_  (
    .A(\__uuf__._144_ ),
    .B(\__uuf__._145_ ),
    .Y(\__uuf__._146_ )
  );
  NAND \__uuf__._389_  (
    .A(\__uuf__._184_ ),
    .B(\__uuf__._146_ ),
    .Y(\__uuf__._147_ )
  );
  NAND \__uuf__._390_  (
    .A(\__BoundaryScanRegister_input_5__.dout ),
    .B(\__uuf__._183_ ),
    .Y(\__uuf__._148_ )
  );
  NAND \__uuf__._391_  (
    .A(\__uuf__._147_ ),
    .B(\__uuf__._148_ ),
    .Y(\__uuf__._009_ )
  );
  NOR \__uuf__._392_  (
    .A(\__uuf__._156_ ),
    .B(\__BoundaryScanRegister_output_9__.sin ),
    .Y(\__uuf__._149_ )
  );
  NOR \__uuf__._393_  (
    .A(\__uuf__._188_ ),
    .B(\__uuf__._149_ ),
    .Y(\__uuf__._150_ )
  );
  NOR \__uuf__._394_  (
    .A(\__BoundaryScanRegister_input_6__.dout ),
    .B(\__uuf__._184_ ),
    .Y(\__uuf__._151_ )
  );
  NOR \__uuf__._395_  (
    .A(\__uuf__._150_ ),
    .B(\__uuf__._151_ ),
    .Y(\__uuf__._010_ )
  );
  NOR \__uuf__._396_  (
    .A(\__uuf__._155_ ),
    .B(\__BoundaryScanRegister_output_9__.sin ),
    .Y(\__uuf__._152_ )
  );
  NOR \__uuf__._397_  (
    .A(\__uuf__._183_ ),
    .B(\__uuf__._152_ ),
    .Y(\__uuf__._153_ )
  );
  NOR \__uuf__._398_  (
    .A(\__BoundaryScanRegister_input_7__.dout ),
    .B(\__uuf__._184_ ),
    .Y(\__uuf__._154_ )
  );
  NOR \__uuf__._399_  (
    .A(\__uuf__._153_ ),
    .B(\__uuf__._154_ ),
    .Y(\__uuf__._011_ )
  );
  DFFSR \__uuf__._400_  (
    .C(clk),
    .D(_018_),
    .Q(product[0]),
    .R(reset),
    .S(1'h0)
  );
  DFFSR \__uuf__._401_  (
    .C(clk),
    .D(_019_),
    .Q(product[1]),
    .R(reset),
    .S(1'h0)
  );
  DFFSR \__uuf__._402_  (
    .C(clk),
    .D(_020_),
    .Q(product[2]),
    .R(reset),
    .S(1'h0)
  );
  DFFSR \__uuf__._403_  (
    .C(clk),
    .D(_021_),
    .Q(product[3]),
    .R(reset),
    .S(1'h0)
  );
  DFFSR \__uuf__._404_  (
    .C(clk),
    .D(_022_),
    .Q(product[4]),
    .R(reset),
    .S(1'h0)
  );
  DFFSR \__uuf__._405_  (
    .C(clk),
    .D(_023_),
    .Q(product[5]),
    .R(reset),
    .S(1'h0)
  );
  DFFSR \__uuf__._406_  (
    .C(clk),
    .D(_024_),
    .Q(product[6]),
    .R(reset),
    .S(1'h0)
  );
  DFFSR \__uuf__._407_  (
    .C(clk),
    .D(_025_),
    .Q(product[7]),
    .R(reset),
    .S(1'h0)
  );
  DFFSR \__uuf__._408_  (
    .C(clk),
    .D(_026_),
    .Q(\__uuf__.control_module0.m0 ),
    .R(reset),
    .S(1'h0)
  );
  DFFSR \__uuf__._409_  (
    .C(clk),
    .D(_027_),
    .Q(\__uuf__.datapath_module0.multiplier [1]),
    .R(reset),
    .S(1'h0)
  );
  DFFSR \__uuf__._410_  (
    .C(clk),
    .D(_028_),
    .Q(\__uuf__.datapath_module0.multiplier [2]),
    .R(reset),
    .S(1'h0)
  );
  DFFSR \__uuf__._411_  (
    .C(clk),
    .D(_029_),
    .Q(\__uuf__.datapath_module0.multiplier [3]),
    .R(reset),
    .S(1'h0)
  );
  DFFSR \__uuf__._412_  (
    .C(clk),
    .D(_030_),
    .Q(\__uuf__.datapath_module0.multiplicand [0]),
    .R(reset),
    .S(1'h0)
  );
  DFFSR \__uuf__._413_  (
    .C(clk),
    .D(_031_),
    .Q(\__uuf__.datapath_module0.multiplicand [1]),
    .R(reset),
    .S(1'h0)
  );
  DFFSR \__uuf__._414_  (
    .C(clk),
    .D(_032_),
    .Q(\__uuf__.datapath_module0.multiplicand [2]),
    .R(reset),
    .S(1'h0)
  );
  DFFSR \__uuf__._415_  (
    .C(clk),
    .D(_033_),
    .Q(\__uuf__.datapath_module0.multiplicand [3]),
    .R(reset),
    .S(1'h0)
  );
  DFFSR \__uuf__._416_  (
    .C(clk),
    .D(_034_),
    .Q(\__uuf__.datapath_module0.multiplicand [4]),
    .R(reset),
    .S(1'h0)
  );
  DFFSR \__uuf__._417_  (
    .C(clk),
    .D(_035_),
    .Q(\__uuf__.datapath_module0.multiplicand [5]),
    .R(reset),
    .S(1'h0)
  );
  DFFSR \__uuf__._418_  (
    .C(clk),
    .D(_036_),
    .Q(\__uuf__.datapath_module0.multiplicand [6]),
    .R(reset),
    .S(1'h0)
  );
  DFFSR \__uuf__._419_  (
    .C(clk),
    .D(_037_),
    .Q(\__uuf__.datapath_module0.multiplicand [7]),
    .R(reset),
    .S(1'h0)
  );
  DFFSR \__uuf__._420_  (
    .C(clk),
    .D(_038_),
    .Q(\__BoundaryScanRegister_output_9__.sin ),
    .R(reset),
    .S(1'h0)
  );
  assign \__uuf__.datapath_module0.multiplier [0] = \__uuf__.control_module0.m0 ;
endmodule

